name: Build and Release Aligned Client

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: aligned-x86
          - os: macos-latest
            artifact_name: aligned-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build batcher client
        run: make build_batcher_client
      
      - name: Rename binary
        run: mv batcher/target/release/aligned ${{ matrix.artifact_name }}
  
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact_name }}
